<?php
/**
 * @var \Straumur\Payment\Block\Info $block
 */
?>
<div class="payment-method straumur-payment">
    <strong><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></strong>
    
    <?php $specificInfo = $block->getSpecificInformation(); ?>
    <?php if (!empty($specificInfo)): ?>
        <div class="payment-details">
            <dl class="payment-method-info">
                <?php foreach ($specificInfo as $label => $value): ?>
                    <dt><?= $block->escapeHtml($label) ?>:</dt>
                    <dd><?= $block->escapeHtml($value) ?></dd>
                <?php endforeach; ?>
            </dl>
        </div>
    <?php endif; ?>
</div>
